name: Java CI with Maven
on:
  push: 
    branches: [main]
    
    
jobs:
    builds:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Java packagee 
        run: mvn clean install -f Javarepo1/pom.xml
      - name: SonarCloud Scan
        run: mvn sonar:sonar -f Javarepo1/pom.xml  -Dsonar.projectKey=git-yogeshsharma87 -Dsonar.organization=Yogesh -Dsonar.branch.name=main -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=71b0f5014cb41cf9b805968f7a0630a778f362fc
